package com.crickscore.producer.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;

import java.time.Instant;
import java.util.UUID;

/**
 * Immutable domain event representing a single ball delivery in a T20 cricket match.
 *
 * <p><b>Kafka Routing:</b>
 * <ul>
 *   <li>Topic: {@code t20-match-scores}</li>
 *   <li>Partition Key: {@code matchId} — guarantees strict per-match ordering.</li>
 * </ul>
 *
 * <p><b>DynamoDB Key Design:</b>
 * <ul>
 *   <li>PK: {@code matchId}</li>
 *   <li>SK: {@code inning#over#ball} (zero-padded for lexicographic sort)</li>
 * </ul>
 *
 * <p><b>Ordering guarantee:</b> All events for a given {@code matchId} land on the same
 * Kafka partition. A single consumer thread processes each partition, so delivery is
 * strictly ordered (inning → over → ball).
 *
 * <p><b>Idempotency:</b> {@code eventId} is a UUID generated by the producer.
 * Consumers use a conditional DynamoDB write (attribute_not_exists PK) to deduplicate.
 */
@Builder(toBuilder = true)
@JsonInclude(Include.NON_NULL)
public record ScoreEvent(

        /**
         * Globally unique event identifier (UUID v4).
         * Used by consumers for idempotency — DynamoDB conditional write enforces uniqueness.
         * Default: auto-generated if not supplied.
         */
        @NotBlank(message = "eventId must not be blank")
        String eventId,

        /**
         * Unique match identifier.
         * Acts as the Kafka partition key — all balls for the same match land on one partition.
         * Format: {@code "IPL-2025-MI-CSK-001"} or any opaque string agreed with upstream.
         */
        @NotBlank(message = "matchId must not be blank")
        String matchId,

        /**
         * Innings number: 1 (first innings) or 2 (second innings).
         */
        @NotNull(message = "inning must not be null")
        @Min(value = 1, message = "inning must be 1 or 2")
        @Max(value = 2, message = "inning must be 1 or 2")
        Integer inning,

        /**
         * Over number within the innings, 0-indexed (0–19 for T20).
         */
        @NotNull(message = "over must not be null")
        @Min(value = 0, message = "over must be between 0 and 19")
        @Max(value = 19, message = "over must be between 0 and 19")
        Integer over,

        /**
         * Ball number within the over, 1-indexed (1–6, extra deliveries may exceed 6).
         */
        @NotNull(message = "ball must not be null")
        @Min(value = 1, message = "ball must be at least 1")
        @Max(value = 9, message = "ball must be at most 9 (including extras)")
        Integer ball,

        /**
         * Batting team code/name. E.g. "MI", "CSK".
         */
        @NotBlank(message = "team must not be blank")
        String team,

        /**
         * Runs scored off this delivery (0–6 for a single legal delivery).
         */
        @NotNull(message = "runs must not be null")
        @Min(value = 0, message = "runs must be >= 0")
        @Max(value = 6,  message = "runs must be <= 6")
        Integer runs,

        /**
         * Extras on this delivery (wides, no-balls, byes, leg-byes).
         * Null or 0 if none.
         */
        @Min(value = 0, message = "extras must be >= 0")
        Integer extras,

        /**
         * Whether a wicket fell on this delivery.
         */
        @NotNull(message = "wicket must not be null")
        Boolean wicket,

        /**
         * Cumulative team total (runs) at the end of this delivery.
         */
        @NotNull(message = "totalRuns must not be null")
        @Min(value = 0, message = "totalRuns must be >= 0")
        Integer totalRuns,

        /**
         * Cumulative wickets fallen at the end of this delivery (0–10).
         */
        @NotNull(message = "wickets must not be null")
        @Min(value = 0,  message = "wickets must be >= 0")
        @Max(value = 10, message = "wickets must be <= 10")
        Integer wickets,

        /**
         * UTC timestamp when this ball was bowled / event was produced.
         * Serialised as ISO-8601 string: {@code "2025-04-15T14:32:01Z"}.
         */
        @NotNull(message = "timestamp must not be null")
        @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "UTC")
        Instant timestamp

) {

    /**
     * Canonical sort key for DynamoDB: {@code "inning#over#ball"} with zero-padding
     * to ensure correct lexicographic ordering.
     *
     * <p>Examples:
     * <pre>
     *   inning=1, over=0, ball=1  →  "1#00#1"
     *   inning=1, over=19, ball=6 →  "1#19#6"
     *   inning=2, over=0, ball=1  →  "2#00#1"
     * </pre>
     */
    public String eventSequence() {
        return "%d#%02d#%d".formatted(inning, over, ball);
    }

    /**
     * Factory method: create a new ScoreEvent with an auto-generated {@code eventId}
     * and the current UTC timestamp if not explicitly set.
     *
     * @return a new {@code ScoreEvent} with {@code eventId} and {@code timestamp} populated.
     */
    public static ScoreEvent withDefaults(ScoreEvent prototype) {
        return prototype.toBuilder()
                .eventId(prototype.eventId() != null ? prototype.eventId() : UUID.randomUUID().toString())
                .timestamp(prototype.timestamp() != null ? prototype.timestamp() : Instant.now())
                .build();
    }
}
