package com.crickscore.consumer.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;

import java.time.Instant;
import java.util.UUID;

/**
 * Immutable domain event representing a single ball delivery in a T20 cricket
 * match.
 *
 * <p>
 * This is a <b>local copy</b> of the producer's {@code ScoreEvent} model.
 * Both services share the same JSON wire format; a future
 * {@code t20-score-common}
 * shared module (see TASK-09.6 note) could eliminate this duplication.
 *
 * <p>
 * <b>Kafka Routing (producer side):</b>
 * <ul>
 * <li>Topic: {@code t20-match-scores}</li>
 * <li>Partition Key: {@code matchId} — guarantees strict per-match
 * ordering.</li>
 * </ul>
 *
 * <p>
 * <b>DynamoDB Key Design:</b>
 * <ul>
 * <li>PK: {@code matchId}</li>
 * <li>SK: {@code eventSequence()} → {@code "inning#over#ball"}
 * (zero-padded)</li>
 * </ul>
 *
 * <p>
 * <b>Idempotency:</b> {@code eventId} is a UUID generated by the producer.
 * The consumer uses a conditional DynamoDB write
 * ({@code attribute_not_exists(matchId)})
 * to reject duplicate writes without treating them as errors.
 *
 * <p>
 * <b>Future:</b> Extract to {@code t20-score-common} module when the model
 * stabilises, to keep producer and consumer in sync automatically.
 */
@Builder(toBuilder = true)
@JsonInclude(Include.NON_NULL)
public record ScoreEvent(

        /**
         * Globally unique event identifier (UUID v4).
         * Used by the consumer for idempotency — DynamoDB conditional write enforces
         * uniqueness.
         */
        @NotBlank(message = "eventId must not be blank") String eventId,

        /**
         * Unique match identifier.
         * Acts as the Kafka partition key — all balls for the same match land on one
         * partition.
         * Format: {@code "IPL-2025-MI-CSK-001"} or any opaque string.
         */
        @NotBlank(message = "matchId must not be blank") String matchId,

        /**
         * Innings number: 1 (first innings) or 2 (second innings).
         */
        @NotNull(message = "inning must not be null") @Min(value = 1, message = "inning must be 1 or 2") @Max(value = 2, message = "inning must be 1 or 2") Integer inning,

        /**
         * Over number within the innings, 0-indexed (0–19 for T20).
         */
        @NotNull(message = "over must not be null") @Min(value = 0, message = "over must be between 0 and 19") @Max(value = 19, message = "over must be between 0 and 19") Integer over,

        /**
         * Ball number within the over, 1-indexed (1–6, extra deliveries may exceed 6).
         */
        @NotNull(message = "ball must not be null") @Min(value = 1, message = "ball must be at least 1") @Max(value = 9, message = "ball must be at most 9 (including extras)") Integer ball,

        /**
         * Batting team code/name. E.g. "MI", "CSK".
         */
        @NotBlank(message = "team must not be blank") String team,

        /**
         * Runs scored off this delivery (0–6 for a single legal delivery).
         */
        @NotNull(message = "runs must not be null") @Min(value = 0, message = "runs must be >= 0") @Max(value = 6, message = "runs must be <= 6") Integer runs,

        /**
         * Extras on this delivery (wides, no-balls, byes, leg-byes). Null or 0 if none.
         */
        @Min(value = 0, message = "extras must be >= 0") Integer extras,

        /**
         * Whether a wicket fell on this delivery.
         */
        @NotNull(message = "wicket must not be null") Boolean wicket,

        /**
         * Cumulative team total (runs) at the end of this delivery.
         */
        @NotNull(message = "totalRuns must not be null") @Min(value = 0, message = "totalRuns must be >= 0") Integer totalRuns,

        /**
         * Cumulative wickets fallen at the end of this delivery (0–10).
         */
        @NotNull(message = "wickets must not be null") @Min(value = 0, message = "wickets must be >= 0") @Max(value = 10, message = "wickets must be <= 10") Integer wickets,

        /**
         * UTC timestamp when this ball was bowled / event was produced.
         * Serialised as ISO-8601 string: {@code "2025-04-15T14:32:01Z"}.
         */
        @NotNull(message = "timestamp must not be null") @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "UTC") Instant timestamp

) {

    /**
     * DynamoDB sort key: {@code "inning#over#ball"} zero-padded for lexicographic
     * ordering.
     *
     * <p>
     * Examples:
     * 
     * <pre>
     *   inning=1, over=0,  ball=1  →  "1#00#1"
     *   inning=1, over=19, ball=6  →  "1#19#6"
     *   inning=2, over=0,  ball=1  →  "2#00#1"
     * </pre>
     */
    public String eventSequence() {
        return "%d#%02d#%d".formatted(inning, over, ball);
    }

    /**
     * Factory method: create a new {@link ScoreEvent} with an auto-generated
     * {@code eventId}
     * and the current UTC {@code timestamp} if not already set.
     *
     * <p>
     * Primarily used in testing to avoid boilerplate.
     */
    public static ScoreEvent withDefaults(ScoreEvent prototype) {
        return prototype.toBuilder()
                .eventId(prototype.eventId() != null ? prototype.eventId() : UUID.randomUUID().toString())
                .timestamp(prototype.timestamp() != null ? prototype.timestamp() : Instant.now())
                .build();
    }
}
